exchanges:
  - id: okx
    enabled: true
    use_ws: true
    ob_limit: 5        # OKX supports 5

  - id: kraken
    enabled: true
    use_ws: true
    ob_limit: 10       # KRAKEN REQUIRES one of {10,25,100,500,1000}

  - id: btcmarkets
    enabled: true
    use_ws: false      # REST only
    ob_limit: 10       # safe default for REST fetchOrderBook

  - id: independentreserve
    enabled: true
    use_ws: false
    ob_limit: 10

  - id: coinspot
    enabled: true
    use_ws: false
    ob_limit: 10

  - id: swyftx
    enabled: false
    use_ws: false
