runtime:
  max_trade_aud: 250
  min_profit_bps_after_fees: 70
  min_confidence: 0.60
  stale_ms: 1000
  slippage_bps_buffer: 5
  rest_poll_ms: 500
  csv_flush_every: 1
  dashboard_host: "0.0.0.0"
  dashboard_port: 8000
  tri_start_aud: 100
